name: package dotnet

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build 
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Super-linter
        uses: super-linter/super-linter@v6.1.1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: TACSV
          path: D:\a\TACSV\TACSV\TACSV\bin\Debug\net7.0-windows\
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.1
        with:
          files: D:\a\TACSV\TACSV\TACSV\bin\Debug\net7.0-windows\
          dest: TACSV.zip
      - name: Create Release on GH Releases
        run: gh release create ${{ steps.generate_release_tag.outputs.next_release_tag }} --latest
      - name: Release on GH Releases
        run: gh release upload ${{ steps.generate_release_tag.outputs.next_release_tag }} TACSV.zip
