name: package dotnet

on: [push]
env:
  GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build 
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: TACSV
          path: D:\a\TACSV\TACSV\TACSV\bin\Debug\net7.0-windows\
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.1
        with:
          files: D:\a\TACSV\TACSV\TACSV\bin\Debug\net7.0-windows\
          dest: TACSV.zip
      - name: Create release
        run: gr release create ${{ github.sha }}
      - name: Release on GH Releases
        run: gh release upload ${{ github.sha }} TACSV.zip
